channels:
- conda-forge
dependencies:
- python=3.12.5
- pip<=24.2
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.0
  - lz4==4.3.3
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
